# Sorting with <code>numpy</code>

In [ ]:
import numpy as np

In [ ]:
x = np.random.randint(0, 20, (10,))
x

In [ ]:
np.argsort(x)

In [ ]:
x[np.argsort(x)]

In [ ]:
np.flip(np.argsort(x))

In [ ]:
x[np.flip(np.argsort(x))]

Get the greatest three elements

In [ ]:
num_top = 3

In [ ]:
np.flip(np.argsort(x))[:num_top]

In [ ]:
x[np.flip(np.argsort(x))[:num_top]]

Get the least two elements

In [ ]:
num_bottom = 2

In [ ]:
x[np.flip(np.argsort(x))[-num_bottom:]]

# Selecting a Subset of <code>numpy</code> Columns

A subset of columns can be selected from a <code>numpy</code> array by referencing the column indices in a <code>numpy</code> array or Python list as shown below.  In addition, the selected columns are returned in the order in which they are referenced in the index array.  The same can be done for rows in an analogous manner, although that circumstance is not illustrated here.

In [2]:
import numpy as np
rand_arr = np.arange(36).reshape(6,6)
rand_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [3]:
rand_arr[:,[5,3,1]]

array([[ 5,  3,  1],
       [11,  9,  7],
       [17, 15, 13],
       [23, 21, 19],
       [29, 27, 25],
       [35, 33, 31]])

In [4]:
idx = np.array([2,4,1])
rand_arr[:,idx]

array([[ 2,  4,  1],
       [ 8, 10,  7],
       [14, 16, 13],
       [20, 22, 19],
       [26, 28, 25],
       [32, 34, 31]])

Note that this method returns a copy of the elements form the original array and the original <code>rand_arr</code> remains unaltered.

In [5]:
rand_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

# Detecting Gurobi Model Status

In [ ]:
import numpy as np
import gurobipy as gpy

m = gpy.Model('Status')
x = m.addMVar((2,), vtype=gpy.GRB.BINARY)
m.update()
m.addConstr(x.sum() >= 3)
m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
m.update()
m.optimize()
print(f'Gurobi Model Status: {m.Status}\n\n\n\n\n')

m = gpy.Model('Status')
x = m.addMVar((3,), vtype=gpy.GRB.BINARY)
m.update()
m.addConstr(x.sum() >= 3)
m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
m.update()
m.optimize()
print(f'Gurobi Model Status: {m.Status}')


In [ ]:
import numpy as np
import gurobipy as gpy

done = False
num_var = 2

while not done:
    m = gpy.Model('Status')
    x = m.addMVar((num_var,), vtype=gpy.GRB.BINARY)
    m.update()
    m.addConstr(x.sum() >= 3)
    m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
    m.update()
    m.optimize()
    print(f'Gurobi Model Status: {m.Status}\n\n\n\n\n')

    if m.Status==3:
        num_var += 1
    else:
        done = True

# Providing a Starting Solution

We have already seen how to load a solution file (<code>.sol</code>), which provides a solution from which Gurobi does surther optimization.  You can also provide a starting solution with an <code>*.mst</code> file or use the <code>.Start</code> attribute of a variable.

In [ ]:
import numpy as np
import gurobipy as gpy

m = gpy.Model('Status')
x = m.addMVar((5,), vtype=gpy.GRB.BINARY)
m.update()
x.Start = np.array([0, 1, 1, 0, 1])
m.addConstr(x.sum() >= 3)
m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
m.update()
m.optimize()
print(f'Gurobi Model Status: {m.Status}')

In [ ]:
import numpy as np
import gurobipy as gpy


num_var = 2
done = False
while not done:
    m = gpy.Model('Status')
    x = m.addMVar((num_var,), vtype=gpy.GRB.BINARY)
    m.update()
    m.addConstr(x.sum() >= 3)
    m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
    m.update()
    m.optimize()
    print(f'Gurobi Model Status: {m.Status}\n\n\n\n\n')
    if m.Status == 2:
        done = True
    else:
        num_var +=1