# Sorting with <code>numpy</code>

In [1]:
import numpy as np

In [2]:
x = np.random.randint(0, 20, (10,))
x

array([ 8,  1, 12, 14, 18,  4,  0, 15,  3, 15])

In [3]:
np.argsort(x)

array([6, 1, 8, 5, 0, 2, 3, 7, 9, 4], dtype=int64)

In [5]:
x[np.argsort(x)]

array([ 0,  1,  3,  4,  8, 12, 14, 15, 15, 18])

In [6]:
np.flip(np.argsort(x))

array([4, 9, 7, 3, 2, 0, 5, 8, 1, 6], dtype=int64)

In [7]:
x[np.flip(np.argsort(x))]

array([18, 15, 15, 14, 12,  8,  4,  3,  1,  0])

Get the greatest three elements

In [9]:
num_top = 3

In [10]:
np.flip(np.argsort(x))[:num_top]

array([4, 9, 7], dtype=int64)

In [11]:
x[np.flip(np.argsort(x))[:num_top]]

array([18, 15, 15])

Get the least two elements

In [12]:
num_bottom = 2

In [13]:
x[np.flip(np.argsort(x))[-num_bottom:]]

array([1, 0])

# Selecting a Subset of <code>numpy</code> Columns

A subset of columns can be selected from a <code>numpy</code> array by referencing the column indices in a <code>numpy</code> array or Python list as shown below.  In addition, the selected columns are returned in the order in which they are referenced in the index array.  The same can be done for rows in an analogous manner, although that circumstance is not illustrated here.

In [ ]:
import numpy as np
rand_arr = np.arange(36).reshape(6,6)
rand_arr

In [ ]:
rand_arr[:,[5,3,1]]

In [ ]:
idx = np.array([2,4,1])
rand_arr[:,idx]

Note that this method returns a copy of the elements form the original array and the original <code>rand_arr</code> remains unaltered.

In [ ]:
rand_arr

# Detecting Gurobi Model Status

In [2]:
import numpy as np
import gurobipy as gpy

m = gpy.Model('Status')
x = m.addMVar((2,), vtype=gpy.GRB.BINARY)
m.update()
m.addConstr(x.sum() >= 3)
m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
m.update()
m.optimize()
print(f'Gurobi Model Status: {m.Status}\n\n\n\n\n')

m = gpy.Model('Status')
x = m.addMVar((3,), vtype=gpy.GRB.BINARY)
m.update()
m.addConstr(x.sum() >= 3)
m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
m.update()
m.optimize()
print(f'Gurobi Model Status: {m.Status}')


Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 2 columns and 2 nonzeros
Model fingerprint: 0xaee6e4fc
Variable types: 0 continuous, 2 integer (2 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [3e+00, 3e+00]
Presolve time: 0.00s

Explored 0 nodes (0 simplex iterations) in 0.01 seconds (0.00 work units)
Thread count was 1 (of 12 available processors)

Solution count 0

Model is infeasible
Best objective -, best bound -, gap -
Gurobi Model Status: 3





Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize 

# Providing a Starting Solution

We have already seen how to load a solution file (<code>.sol</code>), which provides a solution from which Gurobi does surther optimization.  You can also provide a starting solution with an <code>*.mst</code> file or use the <code>.Start</code> attribute of a variable.

In [2]:
import numpy as np
import gurobipy as gpy

m = gpy.Model('Status')
x = m.addMVar((5,), vtype=gpy.GRB.BINARY)
m.update()
x.Start = np.array([0, 1, 1, 0, 1])
m.addConstr(x.sum() >= 3)
m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
m.update()
m.optimize()
print(f'Gurobi Model Status: {m.Status}')

Set parameter Username
Academic license - for non-commercial use only - expires 2024-02-28
Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 5 columns and 5 nonzeros
Model fingerprint: 0xab22f5b7
Variable types: 0 continuous, 5 integer (5 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [3e+00, 3e+00]

Loaded user MIP start with objective 3

Presolve removed 1 rows and 5 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.02 seconds (0.00 work units)
Thread count was 1 (of 12 available processors)

Solution count 1: 3 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.000000000000e+00, best bound 3.000000000000e