# Sorting with <code>numpy</code>

In [1]:
import numpy as np

In [2]:
x = np.random.randint(0, 20, (10,))
x

array([ 8,  1, 12, 14, 18,  4,  0, 15,  3, 15])

In [3]:
np.argsort(x)

array([6, 1, 8, 5, 0, 2, 3, 7, 9, 4], dtype=int64)

In [5]:
x[np.argsort(x)]

array([ 0,  1,  3,  4,  8, 12, 14, 15, 15, 18])

In [6]:
np.flip(np.argsort(x))

array([4, 9, 7, 3, 2, 0, 5, 8, 1, 6], dtype=int64)

In [7]:
x[np.flip(np.argsort(x))]

array([18, 15, 15, 14, 12,  8,  4,  3,  1,  0])

Get the greatest three elements

In [9]:
num_top = 3

In [10]:
np.flip(np.argsort(x))[:num_top]

array([4, 9, 7], dtype=int64)

In [11]:
x[np.flip(np.argsort(x))[:num_top]]

array([18, 15, 15])

Get the least two elements

In [12]:
num_bottom = 2

In [13]:
x[np.flip(np.argsort(x))[-num_bottom:]]

array([1, 0])

# Selecting a Subset of <code>numpy</code> Columns

A subset of columns can be selected from a <code>numpy</code> array by referencing the column indices in a <code>numpy</code> array or Python list as shown below.  In addition, the selected columns are returned in the order in which they are referenced in the index array.  The same can be done for rows in an analogous manner, although that circumstance is not illustrated here.

In [1]:
import numpy as np
rand_arr = np.arange(36).reshape(6,6)
rand_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [2]:
rand_arr[:,[5,3,1]]

array([[ 5,  3,  1],
       [11,  9,  7],
       [17, 15, 13],
       [23, 21, 19],
       [29, 27, 25],
       [35, 33, 31]])

In [3]:
idx = np.array([2,4,1])
rand_arr[:,idx]

array([[ 2,  4,  1],
       [ 8, 10,  7],
       [14, 16, 13],
       [20, 22, 19],
       [26, 28, 25],
       [32, 34, 31]])

Note that this method returns a copy of the elements form the original array and the original <code>rand_arr</code> remains unaltered.

In [4]:
rand_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

# Detecting Gurobi Model Status

In [5]:
import numpy as np
import gurobipy as gpy

m = gpy.Model('Status')
x = m.addMVar((2,), vtype=gpy.GRB.BINARY)
m.update()
m.addConstr(x.sum() >= 3)
m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
m.update()
m.optimize()
print(f'Gurobi Model Status: {m.Status}\n\n\n\n\n')

m = gpy.Model('Status')
x = m.addMVar((3,), vtype=gpy.GRB.BINARY)
m.update()
m.addConstr(x.sum() >= 3)
m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
m.update()
m.optimize()
print(f'Gurobi Model Status: {m.Status}')


Set parameter Username
Academic license - for non-commercial use only - expires 2024-11-06
Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 2 columns and 2 nonzeros
Model fingerprint: 0xaee6e4fc
Variable types: 0 continuous, 2 integer (2 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [3e+00, 3e+00]
Presolve time: 0.00s

Explored 0 nodes (0 simplex iterations) in 0.01 seconds (0.00 work units)
Thread count was 1 (of 12 available processors)

Solution count 0

Model is infeasible
Best objective -, best bound -, gap -
Gurobi Model Status: 3





Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz, instruction set [SSE2|AVX|AVX2

# Providing a Starting Solution

We have already seen how to load a solution file (<code>.sol</code>), which provides a solution from which Gurobi does surther optimization.  You can also provide a starting solution with an <code>*.mst</code> file or use the <code>.Start</code> attribute of a variable.

In [2]:
import numpy as np
import gurobipy as gpy

m = gpy.Model('Status')
x = m.addMVar((5,), vtype=gpy.GRB.BINARY)
m.update()
x.Start = np.array([0, 1, 1, 0, 1])
m.addConstr(x.sum() >= 3)
m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
m.update()
m.optimize()
print(f'Gurobi Model Status: {m.Status}')

Set parameter Username
Academic license - for non-commercial use only - expires 2024-02-28
Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 5 columns and 5 nonzeros
Model fingerprint: 0xab22f5b7
Variable types: 0 continuous, 5 integer (5 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [3e+00, 3e+00]

Loaded user MIP start with objective 3

Presolve removed 1 rows and 5 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.02 seconds (0.00 work units)
Thread count was 1 (of 12 available processors)

Solution count 1: 3 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.000000000000e+00, best bound 3.000000000000e

In [ ]:
import numpy as np
import gurobipy as gpy


num_var = 2
done = False
while not done:
    m = gpy.Model('Status')
    x = m.addMVar((num_var,), vtype=gpy.GRB.BINARY)
    m.update()
    m.addConstr(x.sum() >= 3)
    m.setObjective(x.sum(), gpy.GRB.MINIMIZE)
    m.update()
    m.optimize()
    print(f'Gurobi Model Status: {m.Status}\n\n\n\n\n')
    if m.Status == 2:
        done = True
    else:
        num_var +=1

Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1 rows, 2 columns and 2 nonzeros
Model fingerprint: 0xaee6e4fc
Variable types: 0 continuous, 2 integer (2 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [3e+00, 3e+00]
Presolve time: 0.00s

Explored 0 nodes (0 simplex iterations) in 0.01 seconds (0.00 work units)
Thread count was 1 (of 12 available processors)

Solution count 0

Model is infeasible
Best objective -, best bound -, gap -
Gurobi Model Status: 3





Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Opt

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



Presolve removed 0 rows and 28440 columns
Presolve time: 0.00s

Explored 0 nodes (0 simplex iterations) in 0.01 seconds (0.01 work units)
Thread count was 1 (of 12 available processors)

Solution count 0

Model is infeasible
Best objective -, best bound -, gap -
Gurobi Model Status: 3





Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 239 rows, 28919 columns and 28919 nonzeros
Model fingerprint: 0x2771b237
Variable types: 0 continuous, 28919 integer (28919 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [3e+00, 3e+00]
Presolve removed 0 rows and 28679 columns
Presolve time: 0.00s

Explored 0 nodes (0 simplex iterations) in 0.01 seconds (0.01 work units)
Thread count was 1 (of 12 avail

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



Presolve removed 0 rows and 970920 columns
Presolve time: 0.10s

Explored 0 nodes (0 simplex iterations) in 0.26 seconds (0.23 work units)
Thread count was 1 (of 12 available processors)

Solution count 0

Model is infeasible
Best objective -, best bound -, gap -
Gurobi Model Status: 3





Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1394 rows, 973709 columns and 973709 nonzeros
Model fingerprint: 0x25e22b5f
Variable types: 0 continuous, 973709 integer (973709 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [3e+00, 3e+00]
Presolve removed 0 rows and 972314 columns
Presolve time: 0.12s

Explored 0 nodes (0 simplex iterations) in 0.27 seconds (0.23 work units)
Thread count was 1 (of 1

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



Presolve removed 0 rows and 1890539 columns
Presolve time: 0.20s

Explored 0 nodes (0 simplex iterations) in 0.54 seconds (0.45 work units)
Thread count was 1 (of 12 available processors)

Solution count 0

Model is infeasible
Best objective -, best bound -, gap -
Gurobi Model Status: 3





Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) W-2235 CPU @ 3.80GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 1945 rows, 1894430 columns and 1894430 nonzeros
Model fingerprint: 0x9adc7a86
Variable types: 0 continuous, 1894430 integer (1894430 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [3e+00, 3e+00]
Presolve removed 0 rows and 1892484 columns
Presolve time: 0.22s

Explored 0 nodes (0 simplex iterations) in 0.52 seconds (0.45 work units)
Thread count was 1