# Problem 3.1-3

![dist_problem](LPwGurobiProblem1.jpg)

## Solution with Data in Python Lists

In [27]:
import gurobipy as gpy

# Data
cap_mach = [500, 350, 150]
name_mach = ['Milling', 'Lathe', 'Grinder']
hrs_per_unit = [[9,3,5],[5,4,0],[3,0,2]] # i index for rows (machine type); j index for columns (products)
profit = [50, 20, 25]
name_prod = ['P1', 'P2', 'P3']
num_mach = len(hrs_per_unit)
num_prod = len(hrs_per_unit[0])

# Create Gurobi model
m = gpy.Model('LPWGurobiProblem1')

# Create matrix of decision variables
x = [m.addVar(name=name_prod[j]) for j in range(num_prod)]

# Update model to include variables
m.update()

# Create constraints
m.addConstrs(gpy.quicksum(hrs_per_unit[i][j] * x[j] for j in range(num_prod)) <= cap_mach[i] for i in range(num_mach))
m.addConstr(x[2] <= 20)

# Update to include constraints
m.update()

# Create objective function
m.setObjective((gpy.quicksum(profit[j]*x[j] for j in range(num_prod))), gpy.GRB.MAXIMIZE)

# Update model to include constraints and objective function
m.update()

# Optimize the model
m.optimize()

''' Print decision variable values and other information '''
print('\n\nVariable Sensitivity Analysis')
for v in m.getVars():
    print(f'Variable: {v.varName}, Optimal Value = {v.x}, (LB,UB) = ({v.lb}, {v.ub})')

print('\n\nConstraints')
for c in m.getConstrs():
    print(f'{m.getRow(c)} {c.Sense} {c.RHS}')

''' Print sensitivity analysis information on constraints '''
print('\n\nConstraint Sensitivity Analysis')
for c in m.getConstrs():
    print(f'Constraint: {c.ConstrName}, RHS = {c.RHS}, slack = {c.slack}, (LB,UB) = ({c.SARHSLow}, {c.SARHSUp})')

Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 4 rows, 3 columns and 8 nonzeros
Model fingerprint: 0x79a5bf40
Coefficient statistics:
  Matrix range     [1e+00, 9e+00]
  Objective range  [2e+01, 5e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+01, 5e+02]
Presolve removed 1 rows and 0 columns
Presolve time: 0.01s
Presolved: 3 rows, 3 columns, 7 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    3.3333333e+03   3.956121e+01   0.000000e+00      0s
       2    2.9047619e+03   0.000000e+00   0.000000e+00      0s

Solved in 2 iterations and 0.01 seconds (0.00 work units)
Optimal objective  2.904761905e+03


Variable Sensitivity Analysis
Variable: P1, Optimal Value = 26.19047619047619, (LB,UB) = (0.0, inf)
Variable: P2, Optimal Value = 54.7619047619

## Solution with Data in <code>numpy</code> Arrays

In [7]:
import gurobipy as gpy
import numpy as np

# Data
cap_mach = np.array([500, 350, 150])
name_mach = ['Milling', 'Lathe', 'Grinder']
hrs_per_unit = np.array([[9,3,5],[5,4,0],[3,0,2]])
profit = np.array([50, 20, 25])
name_prod = ['P1', 'P2', 'P3']

# Create Gurobi model
m = gpy.Model('LPWGurobiProblem1')

# Create matrix of decision variables
x = m.addMVar(shape=(3,), vtype=gpy.GRB.CONTINUOUS, name='x') 

# Update model to include variables
m.update()

# Create constraints
#m.addMConstr(hrs_per_unit, x, gpy.GRB.LESS_EQUAL, cap_mach, name='mach_hrs')
m.addConstrs((hrs_per_unit @ x <= cap_mach for _ in range(1)), name='mach_hrs') # generator iterator required despite not needing it
m.addConstr(x[2] <= 20)

# Update to include constraints
m.update()

# Create objective function
m.setObjective(profit @ x, gpy.GRB.MAXIMIZE)

# Update model to include constraints and objective function
m.update()

# Optimize the model
m.optimize()

''' Print decision variable values and other information '''
print('\n\nVariable Sensitivity Analysis')
for v in m.getVars():
    print(f'Variable: {v.varName}, Optimal Value = {v.x}, (LB,UB) = ({v.lb}, {v.ub})')

print('\n\nConstraints')
for c in m.getConstrs():
    print(f'{m.getRow(c)} {c.Sense} {c.RHS}')

''' Print sensitivity analysis information on constraints '''
print('\n\nConstraint Sensitivity Analysis')
for c in m.getConstrs():
    print(f'Constraint: {c.ConstrName}, RHS = {c.RHS}, slack = {c.slack}, (LB,UB) = ({c.SARHSLow}, {c.SARHSUp})')

Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 4 rows, 3 columns and 8 nonzeros
Model fingerprint: 0x79a5bf40
Coefficient statistics:
  Matrix range     [1e+00, 9e+00]
  Objective range  [2e+01, 5e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [2e+01, 5e+02]
Presolve removed 1 rows and 0 columns
Presolve time: 0.01s
Presolved: 3 rows, 3 columns, 7 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    3.3333333e+03   3.956121e+01   0.000000e+00      0s
       2    2.9047619e+03   0.000000e+00   0.000000e+00      0s

Solved in 2 iterations and 0.02 seconds (0.00 work units)
Optimal objective  2.904761905e+03


Variable Sensitivity Analysis
Variable: x[0], Optimal Value = 26.19047619047619, (LB,UB) = (0.0, inf)
Variable: x[1], Optimal Value = 54.761904

# Problem 2: Distribution Problem

![dist_problem](LPwGurobiProblem2.jpg)

## Solution with Data in Python Lists

In [25]:
import gurobipy as grb

# Data
demand_store = [5,4,7,8,5,5]
num_store = len(demand_store)
cap_dc = [10,20,5,15,10]
num_dc = len(cap_dc)
cost_per_truck = [[500,350,250,1300,np.nan,750],
                  [600,200,500,np.nan,850,900],
                  [250, np.nan, 175,300,500,400],
                  [np.nan,875,1000,1100,900,np.nan],
                  [1000,450,np.nan,900,300,800]]
route_restrict = [(0,4), (1,3), (2,1), (3,0), (3,5), (4,2)]
repl = 0

# Create Gurobi model
m = grb.Model('LPWGurobiProblem2')

# Create matrix of decision variables
x = [[m.addVar(name=f'x_{i}_{j}') for j in range(num_store)] for i in range(num_dc)] 

# Update model to include variables
m.update()

# Create constraints
m.addConstrs(gpy.quicksum(x[i][j] for i in range(num_dc)) == demand_store[j] for j in range(num_store))
m.addConstrs(gpy.quicksum(x[i][j] for j in range(num_store)) <= cap_dc[i] for i in range(num_dc))
# Restrict nonfeasible routes
for r in route_restrict:
    m.addConstr(x[r[0]][r[1]] == 0, name=f'Restrict supply from DC {r[0]} to Store {r[1]}')
    cost_per_truck[r[0]][r[1]] = repl

# Update to include constraints
m.update()

# Create objective function
m.setObjective(gpy.quicksum(cost_per_truck[i][j] * x[i][j] for i in range(num_dc) for j in range(num_store)), gpy.GRB.MINIMIZE)

# Update model to include constraints and objective function
m.update()

# Optimize the model
m.optimize()

''' Print decision variable values and other information '''
print('\n\nVariable Sensitivity Analysis')
for v in m.getVars():
    #if var.x > 0.0:
      print(f'Variable: {v.varName}, Optimal Value = {v.x}, Reduced cost = {v.RC}, (LB,UB) = ({v.lb}, {v.ub})')

print('\n\nConstraints')
for c in m.getConstrs():
    print(f'{m.getRow(c)} {c.Sense} {c.RHS}')

''' Print sensitivity analysis information on constraints '''
print('\n\nConstraint Sensitivity Analysis')
for c in m.getConstrs():
    print(f'Constraint: {c.ConstrName}, RHS = {c.RHS}, slack = {c.slack}, (LB,UB) = ({c.SARHSLow}, {c.SARHSUp})')

Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 17 rows, 30 columns and 66 nonzeros
Model fingerprint: 0x10c38f05
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e+02, 1e+03]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e+00, 2e+01]
Presolve removed 6 rows and 6 columns
Presolve time: 0.01s
Presolved: 11 rows, 24 columns, 48 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    9.1750000e+03   1.249400e+01   0.000000e+00      0s
       7    1.5100000e+04   0.000000e+00   0.000000e+00      0s

Solved in 7 iterations and 0.01 seconds (0.00 work units)
Optimal objective  1.510000000e+04


Variable Sensitivity Analysis
Variable: x_0_0, Optimal Value = 0.0, Reduced cost = 0.0, (LB,UB) = (0.0, inf)
Variable: x_0_1, Optimal Val

## Solution with Data in <code>numpy</code> Arrays

In [55]:
import gurobipy as grb
import numpy as np

# Data
demand_store = np.array([5,4,7,8,5,5])
num_store = demand_store.shape[0]
cap_dc = np.array([10,20,5,15,10])
num_dc = cap_dc.shape[0]
cost_per_truck = np.array([[500,350,250,1300,np.nan,750],
                           [600,200,500,np.nan,850,900],
                           [250, np.nan, 175,300,500,400],
                           [np.nan,875,1000,1100,900,np.nan],
                           [1000,450,np.nan,900,300,800]])

# Replace numpy NaN with a large number
cost_per_truck = np.nan_to_num(cost_per_truck, nan=1000000)

# Create Gurobi model
m = grb.Model('LPWGurobiProblem2')

# Create matrix of decision variables
x = m.addMVar(shape=(5,6), vtype=grb.GRB.CONTINUOUS, name='x') 

# Update model to include variables
m.update()

# Create constraints
m.addConstrs((x.sum(axis=0) == demand_store for _ in range(1)), name='dem_store') # generator iterator required despite not needing it
m.addConstrs((x.sum(axis=1) <= cap_dc for _ in range(1)), name='cap_dc')

# Update to include constraints
m.update()

# Create objective function
m.setObjective((cost_per_truck * x).sum(), grb.GRB.MINIMIZE)

# Update model to include constraints and objective function
m.update()

# Optimize the model
m.optimize()

''' Print decision variable values and other information '''
print('\n\nVariable Sensitivity Analysis')
for v in m.getVars():
    #if var.x > 0.0:
      print(f'Variable: {v.varName}, Optimal Value = {v.x}, Reduced cost = {v.RC}, (LB,UB) = ({v.lb}, {v.ub})')

print('\n\nConstraints')
for c in m.getConstrs():
    print(f'{m.getRow(c)} {c.Sense} {c.RHS}')

''' Print sensitivity analysis information on constraints '''
print('\n\nConstraint Sensitivity Analysis')
for c in m.getConstrs():
    print(f'Constraint: {c.ConstrName}, RHS = {c.RHS}, slack = {c.slack}, (LB,UB) = ({c.SARHSLow}, {c.SARHSUp})')

Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 11 rows, 30 columns and 60 nonzeros
Model fingerprint: 0x14ce598b
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e+02, 1e+06]
  Bounds range     [0e+00, 0e+00]
  RHS range        [4e+00, 2e+01]
Presolve time: 0.01s
Presolved: 11 rows, 30 columns, 60 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    9.1750000e+03   2.000000e+01   0.000000e+00      0s
       6    1.5100000e+04   0.000000e+00   0.000000e+00      0s

Solved in 6 iterations and 0.01 seconds (0.00 work units)
Optimal objective  1.510000000e+04


Variable Sensitivity Analysis
Variable: x[0,0], Optimal Value = 0.0, Reduced cost = 0.0, (LB,UB) = (0.0, inf)
Variable: x[0,1], Optimal Value = 0.0, Reduced cost = 250.0, (LB,

## Replacement of NaN Values in <code>numpy</code>

In [54]:
cost_per_truck = np.array([[500,350,250,1300,np.nan,750],
                           [600,200,500,np.nan,850,900],
                           [250, np.nan, 175,300,500,400],
                           [np.nan,875,1000,1100,900,np.nan],
                           [1000,450,np.nan,900,300,800]])
cost_per_truck = np.nan_to_num(cost_per_truck, nan=1000000)
cost_per_truck

array([[5.00e+02, 3.50e+02, 2.50e+02, 1.30e+03, 1.00e+06, 7.50e+02],
       [6.00e+02, 2.00e+02, 5.00e+02, 1.00e+06, 8.50e+02, 9.00e+02],
       [2.50e+02, 1.00e+06, 1.75e+02, 3.00e+02, 5.00e+02, 4.00e+02],
       [1.00e+06, 8.75e+02, 1.00e+03, 1.10e+03, 9.00e+02, 1.00e+06],
       [1.00e+03, 4.50e+02, 1.00e+06, 9.00e+02, 3.00e+02, 8.00e+02]])

In [51]:
cost_per_truck = np.array([[500,350,250,1300,np.nan,750],
                           [600,200,500,np.nan,850,900],
                           [250, np.nan, 175,300,500,400],
                           [np.nan,875,1000,1100,900,np.nan],
                           [1000,450,np.nan,900,300,800]])

np.argwhere(np.isnan(cost_per_truck))

array([[0, 4],
       [1, 3],
       [2, 1],
       [3, 0],
       [3, 5],
       [4, 2]], dtype=int64)

In [52]:
np.argwhere(np.isnan(cost_per_truck)).T

array([[0, 1, 2, 3, 3, 4],
       [4, 3, 1, 0, 5, 2]], dtype=int64)

In [53]:
idx = np.argwhere(np.isnan(cost_per_truck)).T
cost_per_truck[idx[0],idx[1]]

array([nan, nan, nan, nan, nan, nan])

In [49]:
cost_per_truck[idx[0],idx[1]]=1000000
cost_per_truck

array([[5.00e+02, 3.50e+02, 2.50e+02, 1.30e+03, 1.00e+06, 7.50e+02],
       [6.00e+02, 2.00e+02, 5.00e+02, 1.00e+06, 8.50e+02, 9.00e+02],
       [2.50e+02, 1.00e+06, 1.75e+02, 3.00e+02, 5.00e+02, 4.00e+02],
       [1.00e+06, 8.75e+02, 1.00e+03, 1.10e+03, 9.00e+02, 1.00e+06],
       [1.00e+03, 4.50e+02, 1.00e+06, 9.00e+02, 3.00e+02, 8.00e+02]])